name: binet
channels:
  - defaults
dependencies:
  - python=3.6
  - h5py
  - jupyter
  - flask
  - joblib
  - lxml
  - matplotlib
  - networkx
  - numpy
  - openpyxl
  - pandas
  - pip
  - pyodbc
  - scikit-learn
  - scikit-posthocs
  - scipy
  - seaborn
  - xlrd
  - pip:
      - arrow
      - keras
      - pydot
      - pygraphviz
      - sqlalchemy=1.2.10
      - tensorflow
      - tqdm
      - untangle
